<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Tour;

class ToursDesdeWebSeeder extends Seeder
{
    public function run(): void
    {
        $tours = [
            ['nombre' => 'Aguas Termales – Yumagual', 'categoria' => 'nacional'],
            ['nombre' => 'ALTOMAYO MOYOBAMBA – RIOJA', 'categoria' => 'nacional'],
            ['nombre' => 'Arequipa 03D/02N', 'categoria' => 'nacional'],
            ['nombre' => 'Arequipa 04D/03N', 'categoria' => 'nacional'],
            ['nombre' => 'Arequipa 05D/04N', 'categoria' => 'nacional'],
            ['nombre' => 'Arequipa 06D/05N', 'categoria' => 'nacional'],
            ['nombre' => 'Arequipa 07D/06N', 'categoria' => 'nacional'],
            ['nombre' => 'Arequipa 4D/3N', 'categoria' => 'nacional'],
            ['nombre' => 'Avistamiento de Ballenas – Máncora', 'categoria' => 'nacional'],
            ['nombre' => 'Ayacucho 03D/02N', 'categoria' => 'nacional'],
            ['nombre' => 'Ayacucho 04D/03N', 'categoria' => 'nacional'],
            ['nombre' => 'Ayacucho 05D/04N', 'categoria' => 'nacional'],
            ['nombre' => 'Ayacucho 06D/05N', 'categoria' => 'nacional'],
            ['nombre' => 'Ayacucho 07D/06N', 'categoria' => 'nacional'],
            ['nombre' => 'Ayacucho 08D/07N', 'categoria' => 'nacional'],
            ['nombre' => 'Baños del Inca', 'categoria' => 'nacional'],
            ['nombre' => 'Baños del Inca – Fisioterapia', 'categoria' => 'nacional'],
            ['nombre' => 'CAJAMARCA & CHACHAPOYAS 09D/08N', 'categoria' => 'nacional'],
            ['nombre' => 'Cajamarca 04D/03N', 'categoria' => 'nacional'],
            ['nombre' => 'Cajamarca Express 02D/01N', 'categoria' => 'nacional'],
            ['nombre' => 'Cajamarca Express 03D/02N', 'categoria' => 'nacional'],
            ['nombre' => 'Cajamarca Express 04D/03N', 'categoria' => 'nacional'],
            ['nombre' => 'Cajamarca Gastronómico 05D/04N', 'categoria' => 'nacional'],
            ['nombre' => 'Cajamarca Inolvidable 03D/02N', 'categoria' => 'nacional'],
            ['nombre' => 'Cajamarca Inolvidable 04D/03N', 'categoria' => 'nacional'],
            ['nombre' => 'Cajamarca Inolvidable 05D/04N', 'categoria' => 'nacional'],
            ['nombre' => 'Cajamarca Mágica e Inolvidable  08D/07N', 'categoria' => 'nacional'],
            ['nombre' => 'Cajamarca Tradicional 02D/01N', 'categoria' => 'nacional'],
            ['nombre' => 'Cajamarca Tradicional 03D/02N', 'categoria' => 'nacional'],
            ['nombre' => 'Cajamarca Tradicional 04D/03N', 'categoria' => 'nacional'],
            ['nombre' => 'Cajamarca Tradicional 05D/04N', 'categoria' => 'nacional'],
            ['nombre' => 'Caminata Indiana Jones', 'categoria' => 'nacional'],
            ['nombre' => 'CAÑON DE LOS PERDIDOS', 'categoria' => 'nacional'],
            ['nombre' => 'CAÑON DE SHUCTO', 'categoria' => 'nacional'],
            ['nombre' => 'Canotaje en el Río Mayo', 'categoria' => 'nacional'],
            ['nombre' => 'Carnaval Cajamarca 04D/03N', 'categoria' => 'fecha_festiva'],
            ['nombre' => 'Carnaval Cajamarca 05D/04N', 'categoria' => 'fecha_festiva'],
            ['nombre' => 'Carnaval Cajamarca 2025 03D/02N', 'categoria' => 'fecha_festiva'],
            ['nombre' => 'Carnaval de Cajamarca 04D/03N', 'categoria' => 'fecha_festiva'],
            ['nombre' => 'Carnaval de Cajamarca 05D/04N', 'categoria' => 'fecha_festiva'],
            ['nombre' => 'Carnaval de Cajamarca Tradicional 05D/04N', 'categoria' => 'fecha_festiva'],
            ['nombre' => 'Carnaval en Cajamarca 03D/02N', 'categoria' => 'fecha_festiva'],
            ['nombre' => 'CARTAGENA 05D/04N', 'categoria' => 'internacional'],
            ['nombre' => 'CASCADAS DE  CARPISHUYACU  ( BAÑOS TERMALES)', 'categoria' => 'nacional'],
            ['nombre' => 'CASCADAS EL  SALTO DE LA  BRUJA', 'categoria' => 'nacional'],
            ['nombre' => 'CATARATAS DE  AHUASHIYACU', 'categoria' => 'nacional'],
            ['nombre' => 'CATARATAS DE CANGALLO', 'categoria' => 'nacional'],
            ['nombre' => 'CATARATAS DE PILLONES Y  BOSQUE DE PIEDRAS', 'categoria' => 'nacional'],
            ['nombre' => 'Chachapoyas 02D/01N', 'categoria' => 'nacional'],
            ['nombre' => 'Chachapoyas 03D/02N', 'categoria' => 'nacional'],
            ['nombre' => 'Chachapoyas 04D/03N', 'categoria' => 'nacional'],
            ['nombre' => 'Chachapoyas 05D/04N', 'categoria' => 'nacional'],
            ['nombre' => 'Chachapoyas 06D/05N', 'categoria' => 'nacional'],
            ['nombre' => 'Chanchamayo Full Day', 'categoria' => 'full_day'],
            ['nombre' => 'CHAVÍN DE HUÁNTAR – LAGUNA  QUERACOCHA', 'categoria' => 'full_day'],
            ['nombre' => 'Chiclayo 03D/02N', 'categoria' => 'nacional'],
            ['nombre' => 'Chiclayo 04D/03', 'categoria' => 'nacional'],
            ['nombre' => 'Chiclayo 05D/04N', 'categoria' => 'nacional'],
            ['nombre' => 'CHOTA – CUTERVO 2D/1N', 'categoria' => 'nacional'],
            ['nombre' => 'CITY TOUR + MERCADO  DE BRUJAS', 'categoria' => 'nacional'],
            ['nombre' => 'City Tour Ayacucho', 'categoria' => 'nacional'],
            ['nombre' => 'CITY TOUR CHANCHAN', 'categoria' => 'nacional'],
            ['nombre' => 'CITY TOUR CUSCO', 'categoria' => 'nacional'],
            ['nombre' => 'City Tour Huancayo', 'categoria' => 'nacional'],
            ['nombre' => 'City Tour Puno', 'categoria' => 'half_day'],
            ['nombre' => 'City Tours', 'categoria' => 'nacional'],
            ['nombre' => 'CITY TOURS EN  TARAPOTO', 'categoria' => 'nacional'],
            ['nombre' => 'COLCA FULL DAY', 'categoria' => 'full_day'],
            ['nombre' => 'COMPLEJO ARQUEOLÓGICO – KUNTURWASI', 'categoria' => 'nacional'],
            ['nombre' => 'Complejo Arqueológico de Sillustani', 'categoria' => 'nacional'],
            ['nombre' => 'COMPLEJO SECCSACHACA', 'categoria' => 'nacional'],
            ['nombre' => 'Crucero Aruba Jewel of the Seas 08D/07N', 'categoria' => 'crucero'],
            ['nombre' => 'Crucero Caribe Jewel of the Seas 08D/07N', 'categoria' => 'crucero'],
            ['nombre' => 'Crucero Colombia Jewel of the Seas 08D/07N', 'categoria' => 'crucero'],
            ['nombre' => 'CRUCERO EGIPTO 08D/07N', 'categoria' => 'crucero'],
            ['nombre' => 'Crucero Panamá Jewel of the Seas 08D/07N', 'categoria' => 'crucero'],
            ['nombre' => 'Cumbemayo – Ruta Arqueológica', 'categoria' => 'nacional'],
            ['nombre' => 'Cusco 04D/03N', 'categoria' => 'nacional'],
            ['nombre' => 'Cusco 05D/04N', 'categoria' => 'nacional'],
            ['nombre' => 'Cusco 06D/05N', 'categoria' => 'nacional'],
            ['nombre' => 'Cusco 07D/06N', 'categoria' => 'nacional'],
            ['nombre' => 'Cusco 5D/4N', 'categoria' => 'nacional'],
            ['nombre' => 'DECAMERON PUNTA SAL 05D/04N', 'categoria' => 'nacional'],
            ['nombre' => 'Deportes Extremos – NAMORA', 'categoria' => 'nacional'],
            ['nombre' => 'EUROPA FABULOSA 18D/17N', 'categoria' => 'internacional'],
            ['nombre' => 'Fiestas Patrias – Cajamarca Inolvidable 04D/03N', 'categoria' => 'fecha_festiva'],
            ['nombre' => 'Fiestas Patrias – Cajamarca Inolvidable 05D/04N', 'categoria' => 'fecha_festiva'],
            ['nombre' => 'Fiestas Patrias – Cajamarca Tradicional 03D/02N', 'categoria' => 'fecha_festiva'],
            ['nombre' => 'FULL DAY AGUAS TURQUESAS', 'categoria' => 'full_day'],
            ['nombre' => 'FULL DAY AVENTURA EN LUNAHUANA', 'categoria' => 'full_day'],
            ['nombre' => 'FULL DAY CATARATAS  DE GOCTA', 'categoria' => 'full_day'],
            ['nombre' => 'FULL DAY EN CAJABAMBA', 'categoria' => 'full_day'],
            ['nombre' => 'FULL DAY ESPEJO DE LAGUNAS', 'categoria' => 'full_day'],
            ['nombre' => 'FULL DAY HUACHOCOLPA «RUTA DE VOLCANES»', 'categoria' => 'full_day'],
            ['nombre' => 'Full Day Huancaya', 'categoria' => 'full_day'],
            ['nombre' => 'Full Day Huaytapallana', 'categoria' => 'full_day'],
            ['nombre' => 'FULL DAY HUAYTARÁ', 'categoria' => 'full_day'],
            ['nombre' => 'FULL DAY PROVINCIA DE CHOTA', 'categoria' => 'full_day'],
            ['nombre' => 'FULL DAY RUTA DE COLORES “PUKA PONCHO”', 'categoria' => 'full_day'],
            ['nombre' => 'FULL DAY SACSAMARCA', 'categoria' => 'full_day'],
            ['nombre' => 'Granja Porcon', 'categoria' => 'nacional'],
            ['nombre' => 'Hacienda la Colpa', 'categoria' => 'nacional'],
            ['nombre' => 'HALF DAY EL MERCURIO', 'categoria' => 'half_day'],
            ['nombre' => 'HALF DAY PUYAS DE RAYMONDI', 'categoria' => 'half_day'],
            ['nombre' => 'HARMONY OF THE SEAS 09D/08N', 'categoria' => 'nacional'],
            ['nombre' => 'Hotel Disney Resort – Orlando', 'categoria' => 'internacional'],
            ['nombre' => 'HUACACHINA – CITY TOUR', 'categoria' => 'nacional'],
            ['nombre' => 'Huaraz 02D/01N', 'categoria' => 'nacional'],
            ['nombre' => 'Huaraz 03D/02N', 'categoria' => 'nacional'],
            ['nombre' => 'Huaraz 04D/03N', 'categoria' => 'nacional'],
            ['nombre' => 'Huaraz 05D/04N', 'categoria' => 'nacional'],
            ['nombre' => 'Huaraz 3D/2N', 'categoria' => 'nacional'],
            ['nombre' => 'ICA – 06D/05N', 'categoria' => 'nacional'],
            ['nombre' => 'Ica 02D/01N', 'categoria' => 'nacional'],
            ['nombre' => 'Ica 03D/02N', 'categoria' => 'nacional'],
            ['nombre' => 'Ica 04D/03N', 'categoria' => 'nacional'],
            ['nombre' => 'Ica 05D/04N', 'categoria' => 'nacional'],
            ['nombre' => 'Ica 4D/3N', 'categoria' => 'nacional'],
            ['nombre' => 'IGUAZÚ 05D/04N', 'categoria' => 'nacional'],
            ['nombre' => 'IQUITOS CLÁSICO 05D/04N', 'categoria' => 'nacional'],
            ['nombre' => 'ISLAS BALLESTAS', 'categoria' => 'nacional'],
            ['nombre' => 'Islas los Uros', 'categoria' => 'nacional'],
            ['nombre' => 'Islas Uros – Taquile', 'categoria' => 'nacional'],
            ['nombre' => 'IZCUCHACA-CUENCA  “AGUAS CALIENTES”', 'categoria' => 'nacional'],
            ['nombre' => 'Jesús: Ruta del choclo y del Cuy', 'categoria' => 'nacional'],
            ['nombre' => 'JEWEL OF THE SEAS 08D/07N', 'categoria' => 'crucero'],
            ['nombre' => 'LAGO SALINAS', 'categoria' => 'nacional'],
            ['nombre' => 'LAGUNA 69 / LAGUNA  LLANGANUCO', 'categoria' => 'nacional'],
            ['nombre' => 'LAGUNA AZUL', 'categoria' => 'nacional'],
            ['nombre' => 'LAGUNA HUMANTAY', 'categoria' => 'nacional'],
            ['nombre' => 'LAGUNA PARÓN', 'categoria' => 'full_day'],
            ['nombre' => 'Lagunas de alto Perú', 'categoria' => 'nacional'],
            ['nombre' => 'LAGUNAS DE ALTO PERÚ, KUNTUR WASI Y PORCÓN', 'categoria' => 'nacional'],
            ['nombre' => 'LAMAS NATIVO', 'categoria' => 'nacional'],
            ['nombre' => 'LINEAS DE NAZCA', 'categoria' => 'nacional'],
            ['nombre' => 'LLUSHCAPAMPA – Parque de las Esculturas Gigantes', 'categoria' => 'nacional'],
            ['nombre' => 'MACHU PICCHU FULL DAY', 'categoria' => 'full_day'],
            ['nombre' => 'Máncora 02D/01N', 'categoria' => 'nacional'],
            ['nombre' => 'Máncora 03D/02N', 'categoria' => 'nacional'],
            ['nombre' => 'Máncora 04D/03N', 'categoria' => 'nacional'],
            ['nombre' => 'Máncora 05D/04N', 'categoria' => 'nacional'],
            ['nombre' => 'MANGLARES DE TUMBES', 'categoria' => 'full_day'],
            ['nombre' => 'MARAVILLAS DE EUROPA 19D/18N', 'categoria' => 'internacional'],
            ['nombre' => 'MARINER OF THE SEAS 06D/05N', 'categoria' => 'crucero'],
            ['nombre' => 'MAUSOLEOS DE REVASH Y  MUSEO DE LEYMEBAMBA', 'categoria' => 'nacional'],
            ['nombre' => 'MILLPU – AGUAS TURQUESAS', 'categoria' => 'nacional'],
            ['nombre' => 'MONTAÑA DE 7 COLORES', 'categoria' => 'nacional'],
            ['nombre' => 'MOYA-PILCHACA RUTA DE LA SABIDURIA FULL DAY', 'categoria' => 'full_day'],
            ['nombre' => 'MUSEO SICÁN Y BOSQUE DE PÓMAC', 'categoria' => 'nacional'],
            ['nombre' => 'MUSEO TUMBAS  REALES DE SIPÁN', 'categoria' => 'nacional'],
            ['nombre' => 'Namora – Laguna San Nicolás', 'categoria' => 'nacional'],
            ['nombre' => 'NEVADO PASTORURI', 'categoria' => 'nacional'],
            ['nombre' => 'Nor Oriente 07D/06N', 'categoria' => 'nacional'],
            ['nombre' => 'Nor Oriente 09D/08N', 'categoria' => 'nacional'],
            ['nombre' => 'Orlando Disney 09D/08N', 'categoria' => 'internacional'],
            ['nombre' => 'Oxapampa Full Day', 'categoria' => 'full_day'],
            ['nombre' => 'Paraiso de Rocas – Sexemayo', 'categoria' => 'nacional'],
            ['nombre' => 'PARQUE ECO AVENTURA  MANTRA', 'categoria' => 'nacional'],
            ['nombre' => 'PERÚ + ECUADOR 06D/05N', 'categoria' => 'nacional'],
            ['nombre' => 'PIKIMACHAY- HUANTA', 'categoria' => 'nacional'],
            ['nombre' => 'POZUZO', 'categoria' => 'nacional'],
            ['nombre' => 'Puno 03D/02', 'categoria' => 'nacional'],
            ['nombre' => 'Puno 03D/02N', 'categoria' => 'nacional'],
            ['nombre' => 'PUNTA OLÍMPICA/CHACAS', 'categoria' => 'nacional'],
            ['nombre' => 'RESERVA ECOLÓGICA  DE CHAPARRÍ', 'categoria' => 'nacional'],
            ['nombre' => 'RUTA ARQUEÓLOGICA KUELAP HISTÓRICO', 'categoria' => 'nacional'],
            ['nombre' => 'RUTA DEL NORTE 05D/04N', 'categoria' => 'nacional'],
            ['nombre' => 'RUTA DEL SILLAR', 'categoria' => 'nacional'],
            ['nombre' => 'RUTA DEL SUR 08D/07N', 'categoria' => 'escolar'],
            ['nombre' => 'RUTA DEL SUR 18D/17N', 'categoria' => 'nacional'],
            ['nombre' => 'SAN ANDRES 05D/04N', 'categoria' => 'nacional'],
            ['nombre' => 'Santuario de Polloc', 'categoria' => 'nacional'],
            ['nombre' => 'SARCÓFAGOS DE KARAJIA Y MIRADOR DE UTCUBAMBA', 'categoria' => 'nacional'],
            ['nombre' => 'Selva Central 02D/01N', 'categoria' => 'nacional'],
            ['nombre' => 'Selva Central 03D/02N', 'categoria' => 'nacional'],
            ['nombre' => 'Selva Central 04D/03N', 'categoria' => 'nacional'],
            ['nombre' => 'Selva Central 05D/04N', 'categoria' => 'nacional'],
            ['nombre' => 'Selva Central 06D/05N', 'categoria' => 'nacional'],
            ['nombre' => 'Semana Santa – Cajamarca Inolvidable 02D/01N', 'categoria' => 'nacional'],
            ['nombre' => 'Semana Santa – Cajamarca Inolvidable 05D/04N', 'categoria' => 'nacional'],
            ['nombre' => 'Semana Santa – Travel to Cajamarca 03D/02N', 'categoria' => 'nacional'],
            ['nombre' => 'Semana Santa – Travel to Cajamarca 04D/03N', 'categoria' => 'nacional'],
            ['nombre' => 'TAILANDIA 07D/06N', 'categoria' => 'internacional'],
            ['nombre' => 'Tarapoto 04D/03N', 'categoria' => 'nacional'],
            ['nombre' => 'Tarapoto 05D/04N', 'categoria' => 'nacional'],
            ['nombre' => 'Tarapoto 06D/05N', 'categoria' => 'nacional'],
            ['nombre' => 'Tarapoto 07D/06N', 'categoria' => 'nacional'],
            ['nombre' => 'Tortugas Marinas – Máncora', 'categoria' => 'nacional'],
            ['nombre' => 'TOUR  EL BRUJO', 'categoria' => 'nacional'],
            ['nombre' => 'Tour Argentina', 'categoria' => 'internacional'],
            ['nombre' => 'Tour Brasil', 'categoria' => 'internacional'],
            ['nombre' => 'Tour Cartagena', 'categoria' => 'internacional'],
            ['nombre' => 'Tour Completo por Perú', 'categoria' => 'nacional'],
            ['nombre' => 'Tour Ecuador', 'categoria' => 'internacional'],
            ['nombre' => 'Tour Europa', 'categoria' => 'internacional'],
            ['nombre' => 'Tour Huancayo Artesanal', 'categoria' => 'nacional'],
            ['nombre' => 'TOUR LAGUNA DE CONACHE', 'categoria' => 'nacional'],
            ['nombre' => 'Tour México', 'categoria' => 'internacional'],
            ['nombre' => 'TOUR MOCHE', 'categoria' => 'nacional'],
            ['nombre' => 'Tour Monumental', 'categoria' => 'nacional'],
            ['nombre' => 'TOUR RUTA AYMARA', 'categoria' => 'full_day'],
            ['nombre' => 'TOUR RUTA DEL TORITO', 'categoria' => 'nacional'],
            ['nombre' => 'TOUR RUTA QUECHUA', 'categoria' => 'nacional'],
            ['nombre' => 'Tour Tailandia', 'categoria' => 'internacional'],
            ['nombre' => 'TOURS YANAHUARA  + CAMPIÑA', 'categoria' => 'nacional'],
            ['nombre' => 'Trujillo 02D/01N', 'categoria' => 'nacional'],
            ['nombre' => 'Trujillo 03D/02N', 'categoria' => 'nacional'],
            ['nombre' => 'UTOPIA OF THE SEAS 05D/04N', 'categoria' => 'crucero'],
            ['nombre' => 'VALLE PERENÉ', 'categoria' => 'nacional'],
            ['nombre' => 'VALLE SAGRADO – MARAS,  MORAY Y SALINERAS', 'categoria' => 'nacional'],
            ['nombre' => 'Ventanillas de Otuzco', 'categoria' => 'nacional'],
            ['nombre' => 'VIAJE DE CONFRATERNIDAD DECÁMERON PUEBLO 03D/02N', 'categoria' => 'nacional'],
            ['nombre' => 'VIAJE DE CONFRATERNIDAD DECÁMERON PUEBLO 04D/03N', 'categoria' => 'nacional'],
            ['nombre' => 'Viaje Escolar Arequipa', 'categoria' => 'escolar'],
            ['nombre' => 'Viaje Escolar Cajamarca', 'categoria' => 'escolar'],
            ['nombre' => 'Viaje Escolar Cusco', 'categoria' => 'escolar'],
            ['nombre' => 'Viaje Escolar Trujillo', 'categoria' => 'escolar'],
            ['nombre' => 'VILCASHUAMAN – INTIHUATANA', 'categoria' => 'nacional'],
            ['nombre' => 'VILLA RICA', 'categoria' => 'nacional'],
            ['nombre' => 'VILLA RICA OROPESA HALF DAY', 'categoria' => 'half_day'],
            ['nombre' => 'VINÍCOLAS', 'categoria' => 'nacional'],
            ['nombre' => 'VOLCÁN DE PACHAPUPUM', 'categoria' => 'nacional'],
            ['nombre' => 'WARI – QUINUA', 'categoria' => 'nacional'],
        ];

        $this->command->info('Importando ' . count($tours) . ' tours...');

        foreach ($tours as $tour) {
            Tour::updateOrCreate(
                ['nombre' => $tour['nombre']],
                ['categoria' => $tour['categoria'], 'veces_usado' => 0, 'activo' => true]
            );
        }

        $this->command->info('Listo! ' . count($tours) . ' tours.');
    }
}